plugins:
  community_canned_replies_enabled:
    default: true
    client: true
  community_canned_replies_groups:
    default: ""
    type: list
  community_canned_replies_everyone_enabled:
    default: false
    client: true
  community_canned_replies_everyone_can_edit:
    default: false
    client: true
